import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,X,ArrowUpRight,CalendarDays,MapPin,Phone,Headphones,Gamepad2,Store,Utensils,HandCoins,ShieldCheck,School,Users,Accessibility,Plus,Minus} from 'lucide-react';
import './styles.css';

const activities=[['SKATE','🛼','red'],['DJ’S',Headphones,'yellow'],['GAMING',Gamepad2,'purple'],['FUNDRAISING',HandCoins,'green'],['VENDORS',Store,'blue'],['FOOD',Utensils,'orange']];
const Btn=({children,kind='red',href='#register'})=><a className={`btn ${kind}`} href={href}>{children}<ArrowUpRight size={18}/></a>;
function Header(){const [open,setOpen]=useState(false);return <header><a className="skip" href="#main">Skip to content</a><div className="nav"><a href="#home"><img src="/assets/logo.png" className="logo" alt="The Roll Out"/></a><button className="menu" aria-label="Toggle menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} aria-label="Main navigation">{['HOME','ABOUT','RINKS','SCHOOLS','PARENTS','VENDORS','GAMING','CONTACT'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}</nav><div className="nav-actions"><Btn kind="outline">GET INVOLVED</Btn><Btn kind="yellow">GET UPDATES</Btn></div></div></header>}
function Hero(){return <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">ATLANTA'S <b>WEEKLY</b> SKATE EXPERIENCE</p><h1><span>THE</span> ROLL <em>OUT</em></h1><p className="lead">Bringing the culture, the community, and the good vibes together—every week.</p><div className="activities">{activities.map(([n,I,c])=><div className={'activity '+c} key={n}>{typeof I==='string'?<span className="emoji">{I}</span>:<I/>}<strong>{n}</strong></div>)}</div><div className="hero-actions"><Btn>SIGN UP / GET UPDATES</Btn><Btn kind="outline" href="#rink">VIEW RINK DETAILS</Btn></div></div><div className="hero-photo"><img src="/assets/hero-skaters.jpg" alt="Young skaters enjoying a roller skating event"/><div className="paper">A DIFFERENT SCHOOL.<br/>A DIFFERENT RINK.<br/>THE SAME VIBE.<br/><b>EVERY WEEK.</b></div><div className="next"><span>NEXT UP ↩</span><h2>SKATE ZONE</h2><p><MapPin/> 6766 Mt Zion Blvd<br/>Morrow, GA 30260</p><p className="date"><CalendarDays/> DATES DROPPING SOON</p><a href="tel:7709601400"><Phone/> (770) 960-1400</a><Btn kind="yellow" href="#register">GET UPDATES</Btn></div></div></section>}
function Audience(){return <section className="audience" id="about"><article className="card kids"><div><h2>FOR THE <b>KIDS</b></h2><p>Skate. Dance. Compete.<br/>Win prizes. Make memories.</p><Btn kind="yellow" href="#register">EXPLORE</Btn></div><img src="/assets/kids.jpg" alt="Teen enjoying gaming"/></article><article className="card features"><p>🎧 LIVE DJ SETS</p><p>🎮 GAMING TOURNAMENTS</p><p>🎁 PRIZES & GIVEAWAYS</p><p>🏪 VENDORS & FOOD</p><p>🛡️ SAFE, FUN ENVIRONMENT</p></article><article className="card parents" id="parents"><div><h2>FOR <b>PARENTS</b></h2><p>A safe, supervised, positive environment your kids will love.</p><Btn href="#register">SIGN UP</Btn></div><img src="/assets/parents.jpg" alt="Parent and child looking at a phone together"/></article><article className="card schools" id="schools"><School/><h2>FOR <b>SCHOOLS</b></h2><p>Raise funds. Build school spirit.<br/>We handle the experience.</p><Btn kind="green" href="#contact">PARTNER WITH US</Btn></article></section>}
function Rink(){return <section className="rink" id="rink"><div><p className="eyebrow">OUR FIRST RINK</p><h2>SKATE ZONE</h2><p><MapPin/> 6766 Mt Zion Blvd, Morrow, GA 30260</p><p><Phone/> <a href="tel:7709601400">770-960-1400</a></p></div><div className="soon"><span>DATES</span><b>DROPPING SOON</b><p>Join the list and we'll tell you when registration opens.</p><Btn href="#register">NOTIFY ME</Btn></div></section>}
function Register(){const [kids,setKids]=useState([{name:'',age:''}]);const [sent,setSent]=useState(false);const update=(i,k,v)=>setKids(kids.map((x,j)=>j===i?{...x,[k]:v}:x));const submit=e=>{e.preventDefault();setSent(true)};return <section className="register" id="register"><div className="register-intro"><p className="eyebrow">DON'T MISS THE DROP</p><h2>PARENT / GUARDIAN SIGN-UP</h2><p>One quick form. Add your child or teen, and we'll notify you when Skate Zone dates and registration open.</p><div className="privacy"><ShieldCheck/> Parent/guardian information is the primary contact. Keep child information minimal until event registration opens.</div></div>{sent?<div className="success"><h3>YOU'RE ON THE LIST 🎉</h3><p>This demo form is working on the front end. Connect it to your registration/email service before launch to save submissions.</p><button className="btn yellow" onClick={()=>setSent(false)}>ADD ANOTHER FAMILY</button></div>:<form onSubmit={submit}><label>Parent / Guardian Name<input required name="parent" autoComplete="name"/></label><div className="two"><label>Email<input required type="email" name="email" autoComplete="email"/></label><label>Mobile Number<input required type="tel" name="phone" autoComplete="tel"/></label></div>{kids.map((k,i)=><fieldset key={i}><legend>Child / Teen {i+1}</legend><div className="two"><label>First Name<input required value={k.name} onChange={e=>update(i,'name',e.target.value)}/></label><label>Age<input required min="5" max="18" type="number" value={k.age} onChange={e=>update(i,'age',e.target.value)}/></label></div>{kids.length>1&&<button type="button" className="textbtn" onClick={()=>setKids(kids.filter((_,j)=>j!==i))}><Minus/> Remove</button>}</fieldset>)}<button type="button" className="textbtn" onClick={()=>setKids([...kids,{name:'',age:''}])}><Plus/> Add another child</button><label className="check"><input required type="checkbox"/> I am the parent/legal guardian or authorized adult and agree to receive Roll Out event updates.</label><button className="btn red" type="submit">JOIN THE LIST <ArrowUpRight/></button></form>}</section>}
function Footer(){return <><section className="weekly"><h2>WHO'S ROLLING OUT <b>THIS WEEK?</b></h2><p>Dates are dropping soon.</p><Btn kind="outline" href="#register">GET UPDATES</Btn></section><footer id="contact"><img src="/assets/logo.png" alt="The Roll Out"/><div><b>QUICK LINKS</b><a href="#home">Home</a><a href="#rink">Rinks</a><a href="#parents">Parents</a><a href="#schools">Schools</a></div><div><b>GET INVOLVED</b><a href="#register">Family Sign-Up</a><a href="#schools">School Partners</a><a href="#contact">Vendors</a></div><div className="accessible"><Accessibility/><span><b>WE'RE ACCESSIBLE</b><small>Designed for keyboard use, readable contrast and reduced-motion preferences.</small></span></div></footer></>}
function App(){return <><Header/><main id="main"><Hero/><Audience/><Rink/><Register/><Footer/></main></>};createRoot(document.getElementById('root')).render(<App/>);
