const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const menu=$('.menu-toggle'),nav=$('#nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});$$('#nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const modal=$('#signupModal'),form=$('#signupForm'),children=$('#children'),success=$('#success');
function childRow(){const n=children.children.length+1;const row=document.createElement('div');row.className='child-row';row.innerHTML=`<label>Child/Teen Name<input required name="child_name_${n}" autocomplete="off"></label><label>Age<input required type="number" min="3" max="19" name="child_age_${n}"></label><button type="button" class="remove-child" aria-label="Remove child">×</button>`;row.querySelector('.remove-child').onclick=()=>{if(children.children.length>1)row.remove()};children.appendChild(row)}
childRow();$('#addChild').onclick=childRow;
function openModal(){modal.hidden=false;document.body.style.overflow='hidden';setTimeout(()=>$('.modal-close').focus(),10)}function closeModal(){modal.hidden=true;document.body.style.overflow=''}$$('[data-open="signup"]').forEach(b=>b.addEventListener('click',openModal));$('.modal-close').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
form.addEventListener('submit',e=>{e.preventDefault();form.hidden=true;success.hidden=false});
const panel=$('#accessPanel');function openAccess(){panel.hidden=false;$('.panel-close').focus()}function closeAccess(){panel.hidden=true}$('#accessOpen').onclick=openAccess;$('#accessFooter').onclick=openAccess;$('#accessFooter2').onclick=openAccess;$('.panel-close').onclick=closeAccess;
let pct=100;$$('[data-font]').forEach(b=>b.onclick=()=>{pct=Math.max(85,Math.min(130,pct+(b.dataset.font==='+'?10:-10)));document.documentElement.style.setProperty('--base',pct/100*16+'px');$('#fontPct').textContent=pct+'%'});$('#contrast').onclick=()=>document.body.classList.toggle('high-contrast');$('#links').onclick=()=>document.body.classList.toggle('high-links');
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!modal.hidden)closeModal();if(!panel.hidden)closeAccess()}});
